
language: python
python:
  - "3.6"      # current default Python on Travis CI


branches:
  only:
  - /^feature.*$/


# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - cd repo_pkg && python test_travis.py && python hello_git.py

after_success:
  - python ci_tools/increment_version.py
  - git add -u
  - git commit -m "[ci skip] version changed"
  - git push
