name: "Close stale issues"
on:
  schedule:
  - cron: "22 22 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: test
    - run: |
        echo "This is a cron job test"
        date
