name: "Close stale issues"
on:
  schedule:
  - cron: "59 12 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo "This is a cron job test"
        date
        
    - name: Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
          username: 'github-actions-tests',
          icon_emoji: ':octocat:',
          attachments: [{
            color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
            text: `Scheduled tests ${process.env.AS_WORKFLOW} have run in ${process.env.AS_TOOK} with status ${job.status}`
          }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
      if: always()
