name: "Daily SDK Build and Test"
on:
  schedule:
  - cron: "25 9 * * *"
  #- cron: "0 */6 * * *"
    
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v2
    - uses: "actions/setup-python@v2"
      with:
        python-version: "3.7"
              
    - name: test
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        set -ve
        echo "This is a cron job test"
        date
        echo "Print env"
        echo $ {{ github.ref }}
        env
        
        
    - name: Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
          username: 'github-actions-tests',
          icon_emoji: ':octocat:',
          attachments: [{
            color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
            text: `${process.env.AS_WORKFLOW} on ${process.env.AS_REPO} have run in ${process.env.AS_TOOK} with status ${{ job.status }}`
          }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
      if: always()
