# This is a basic workflow to help you get started with Actions

name: ApplicationTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the project
        uses: actions/checkout@master
      
      - name: Move into project directory
        run: |
          echo "Currently in project directory"
          pwd
      
      - name: Build docker images
        run: |
            cd repo_pkg
            docker build -t local .
      - name: Run tests
        run: docker run --rm local
      
      - name: Github context
        run: |
          echo ${{ github.ref }}
          echo ${{ github.base_ref  }}
          
      - name: Bump the version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}    
        run: |
          echo "bumping version"
          sudo apt-get install dos2unix
          dos2unix ci_tools/bumpversion.sh
          bash ci_tools/bumpversion.sh
          

